sudo: required

services:
  - docker

before_install:
  - docker build -t nikolakp/docker-react -f Dockerfile.dev .

script:
  - docker run nikolakp/docker-react npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: elasticbeanstalk-us-west-2-30284294802740237
  bucker_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"  